version: "3.7"

services:
  api:
    command: ["node", "dist/main"]
    image: luissaybe/korean-dictionary-elastic-search
    ports:
      - 9000:80
    volumes:
      - .:/root/project
    depends_on:
      - elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
