version: "3.7"

services:
    api:
      command: ["node", "dist/main"]
      image: luissaybe/korean-dictionary-elastic-search
      environment:
        - DICTIONARY_API_KEY=DICTIONARY_API_KEY
      ports:
        - 80:80
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes:
      - data0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
