version: "3.7"

services:
  api:
    command: ["node", "--max-old-space-size=6144", "dist/main"]
    image: luissaybe/korean-dictionary-elastic-search
    environment:
      - DICTIONARY_API_KEY=DICTIONARY_API_KEY
    ports:
      - 80:80
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
