version: "3.7"

services:
  api:
    command: ["node", "dist/main"]
    image: luissaybe/korean-dictionary-elastic-search
    ports:
      - 443:443
    environment:
      - SSL_CERTS_FOLDER=/root/certs
    volumes:
      - /root/certs:/root/certs
    depends_on:
      - elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
